### ISSUE TITLE
Does not work with sbt 0.13.9

### ISSUE THREAD

**Issue by SRGOM** [dscleaver/sbt-quickfix#19]
QuickFixLogger gets initialized but errors/warnings are not handled.

**Comment by leifwickland** [comment]
+1 
As near as I can tell the problem started in 0.13.8. It works for me in 0.13.7.
At least part of the problem is that the quickfix file isn't being written.

**Comment by zmre** [comment]
+1

**Comment by brendanmaguire** [comment]
Works for me with sbt 0.13.9 . Might not be the correct way to do it?

**Comment by adelbertc** [comment]
Should be fixed by https://github.com/dscleaver/sbt-quickfix/pull/20
